### ISSUE TITLE
openrave-ros automated builds failing

### ISSUE THREAD

**Issue by gavanderhoorn** [personalrobotics/docker-public-images#1]
Just noticed that the automated builds of `openrave-ros` have been failing for quite some time (at least for 5 months, according to [hub/personalrobotics/ros-openrave/builds](https://hub.docker.com/r/personalrobotics/ros-openrave/builds)).

The [latest one failed](https://hub.docker.com/r/personalrobotics/ros-openrave/builds/beyrsuikqt3xry9odweypyj/) with the following error:

```
Step 6/6 : RUN apt-get update && apt-get install -y pr-openrave && rm -rf /var/lib/apt/lists/*
[...]
Failed to fetch http://packages.personalrobotics.ri.cmu.edu/public/dists/trusty/main/binary-amd64/Packages
   404 Not Found E: Some index files failed to download.
   They have been ignored, or old ones used instead.
```

This then makes the entire build fail.

**Comment by gavanderhoorn** [comment]
It would appear that `packages.personalrobotics.ri.cmu.edu` is returning `404`s for every request.

**Comment by gavanderhoorn** [comment]
Should the `Dockerfile` be using `ppa:personalrobotics/ppa` instead? That would appear to have recent builds of `pr-openrave`.

**Comment by psigen** [comment]
I think this entire Dockerfile is a bit out of date since the lab itself moved to UW.

@brianhou: do you know what the status of our automated docker builds is?

**Comment by gavanderhoorn** [comment]
> since the lab itself moved to UW

UW?

Using the PPA seems to work: [Dockerfile](https://github.com/gavanderhoorn/docker-public-images/blob/use_ppa/ros-openrave/Dockerfile).

**Comment by psigen** [comment]
Sorry, let me clarify: the Personal Robotics Lab (the organization that owns this repo) was originally at Carnegie Mellon University, but it recently moved to the University of Washington, so a bunch of our servers and other infrastructure have changed in the past months and we have been working on migrating.

Thanks for the PR.  It looks fine, we can merge as soon as I get a review on it.

**Comment by gavanderhoorn** [comment]
@psigen wrote:
> Thanks for the PR.

well, it wasn't exactly a PR, but thanks for updating the `Dockerfile`.

[Latest build](https://hub.docker.com/r/personalrobotics/ros-openrave/builds/) seems to have gone ok again 👍.
