### ISSUE TITLE
ros-openrave: trigger build?

### ISSUE THREAD

**Issue by gavanderhoorn** [personalrobotics/docker-public-images#3]
Last build on Docker Hub appears to have completed three months ago.

Did something change or are automated / periodic builds not enabled?

**Comment by psigen** [comment]
Hi @gavanderhoorn:

We do _automated_ but not _periodic_ builds on this repository.  It is triggered by pushes into the repo or updates to the upstream *ros:indigo-ros-base* image.  My guess is that neither of these had been updated in some time.

**Comment by psigen** [comment]
I manually triggered a build 30 minutes ago and it seemed to complete just fine, so I am going to close this issue for now.  Feel free to reopen if there is something else that needs to be updated.

**Comment by gavanderhoorn** [comment]
Makes sense. Thanks for triggering a build.

Would it be an idea to enable periodic builds?

Perhaps tagged by date or openrave version?
